### ISSUE TITLE
i know a meme

### ISSUE THREAD

**Issue by AlexHGaming** [XtremePlayzCODE/memes#1]
my life ;-;

**Comment by XtremePlayzCODE** [comment]
[93581ae](https://github.com/XtremePlayzCODE/memes/commit/93581aeb693551f98480649de36653154cb93362)

**Comment by XtremePlayzCODE** [comment]
feel free to add more memes, i need tons more

**Comment by XtremePlayzCODE** [comment]
they **must** be in number format because i have an API that uses this, and it requires the numbers
